# Generated by Django 3.2.4 on 2021-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
