# Generated by Django 3.2.4 on 2021-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default='capture.jpg', null=True, upload_to=''),
        ),
    ]
