# Generated by Django 3.2.4 on 2021-09-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210917_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='writer',
            field=models.CharField(default='@writersname', max_length=200),
        ),
    ]
