# Generated by Django 3.2.4 on 2021-09-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifcation', '0001_initial'),
        ('blog', '0008_alter_blogs_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifcation.profile'),
        ),
    ]
